### ISSUE TITLE
Have source maps included as an option

### ISSUE THREAD

**Issue by kjpluck** [beingnin/Azure-Devops-Extension-Sass-Compiler#3]
Hi!

Thank you for creating this! Really useful, thanks!

Would be great if you could make including source-maps as a configurable option! We build internal mock design sites for testing styles and having the css.map on them is very useful.

Keep up the excellent work!

**Comment by beingnin** [comment]
@kjpluck the requirements are clear for me. Will try to incorporate it soon. happy knowing the extension is helpful to you

**Comment by kjpluck** [comment]
Excellent! Thanks for the update!

**Comment by beingnin** [comment]
@kjpluck generating source maps is added as a new feature. Use it as per the screenshot below. thank you!
<img width="100" alt="image" src="https://user-images.githubusercontent.com/25583764/216664018-09ee8529-b15c-4c62-8afa-fae37e445220.png">

**Comment by kjpluck** [comment]
Great stuff! Thank you!

It's a pity I don't work for the company where I was using it anymore 🙂

Much appreciated though 😉

**Comment by beingnin** [comment]
Oh God I procrastinated on this too. Sorry man 🙁
